### ISSUE TITLE
Mouse cursor doesn't revert after resizing

### ISSUE THREAD

**Issue by runeloader** [kirill-grouchnikov/substance#10]
The mouse cursor doesn't always revert to the normal pointer after resizing or hovering over the border to resize, it will simply stay in it's resizing state until manually set back to the normal cursor. 
Happens more frequently on OSX than on Windows but does occur on both.

**Comment by kirill-grouchnikov** [comment]
What is the version of Substance you're using?

**Comment by runeloader** [comment]
The latest, from this repository

**Comment by kirill-grouchnikov** [comment]
Building from the latest master sources? I played with resizing a test app on my Mac, and I don't see the cursor getting stuck.

**Comment by runeloader** [comment]
Yep. I think it mainly occurs if you go from 1 resizable state to another without returning to the normal cursor in between.

**Comment by kirill-grouchnikov** [comment]
Saw the same issue under Metal. The latest commit has a somewhat awkward fix. Let me know if this fixes it on your side.

**Comment by kirill-grouchnikov** [comment]
Uploaded the latest binaries to the drop/ folder. You can also compile from sources. Should be identical.

**Comment by runeloader** [comment]
Alright, thanks. I'll have a look now!

**Comment by runeloader** [comment]
Still having the same issue

**Comment by kirill-grouchnikov** [comment]
Will be tracked in kirill-grouchnikov/radiance#7

See http://www.pushing-pixels.org/2018/05/23/hello-radiance.html for context.
