### ISSUE TITLE
"Vertical" tabs for JTabbedPane

### ISSUE THREAD

**Issue by stefan-reich** [kirill-grouchnikov/substance#11]
Hi!

A very useful feature was found in an earlier version of Substance: [vertical tabs](https://svn.java.net/svn/substance~svn/tags/rc_4_1_lima/www/docs/clientprops/TabbedPaneVerticalOrientation.html)!

Will it return to the current version? Seems like a beautiful thing to have.

Greetings,
Stefan

**Comment by kirill-grouchnikov** [comment]
Left / right tabs are rotated by default in Substance. No need for setting an extra client property.

**Comment by stefan-reich** [comment]
Ah! Very good. Now this is pretty: [Green Tabs](http://tinybrain.de/1006358)
