### ISSUE TITLE
Plans for Office 2010+ ribbons and LaFs?

### ISSUE THREAD

**Issue by utybo** [kirill-grouchnikov/substance#12]
Are there any plans for making a File menu in the ribbon like the ones found in post-2007 versions of MS-Office and/or Look and Feel for Office 2010/3/6?

**Comment by kirill-grouchnikov** [comment]
Worth looking into that. No promises for now since that would depend on how much work would be involved. I'd probably not want to support multiple styles. So if anything, it'd be a global refresh of the style for all the components.

**Comment by kirill-grouchnikov** [comment]
This will be tracked by https://github.com/kirill-grouchnikov/flamingo/issues/19
