### ISSUE TITLE
Retina 200%

### ISSUE THREAD

**Issue by plingsi** [kirill-grouchnikov/substance#13]
When running the ribbon application on a Hi DPI 200% I get the following result:
![image](https://cloud.githubusercontent.com/assets/10544270/22399408/20a14048-e59c-11e6-9c72-e0460c59263a.png)
The task menu is behind. How can I fix this?

**Comment by kirill-grouchnikov** [comment]
Brevity is not very friendly for bug reports.

What is the version of Substance / Flamingo that you're using?
What OS version you're running?
What Java version you're running?
What exactly is Hi DPI 200%?
What is "task menu is behind"?

Also, to make things much easier I'd need to see the complete standalone code for this bug report.

**Comment by plingsi** [comment]
Sorry for my short post!
I am using the latest builds from drop on Windows 10 with JDK jdk1.8.0_77. My screen resolution is 2880 x 1800 with a scaling factor of 200% (Recomended by Windows). As you can see in the Picture from the first post the "Task" height should be larger. The code is as follows:

private void createRibbon() {
        JRibbonBand[] homeBandArray = new JRibbonBand[1];
        JRibbonBand mouse = new JRibbonBand("Band", new EmptyResizableIcon(16));
        mouse.setResizePolicies(CoreRibbonResizePolicies.getCorePoliciesNone(mouse));
        mouse.startGroup();
        JCommandToggleButton button = new JCommandToggleButton("Button", ImageWrapperResizableIcon.getIcon(getClass().getResource("/images/ribbonbar/length.png"), new Dimension(64, 64)));
        mouse.addCommandButton(button, RibbonElementPriority.TOP);
        homeBandArray[0] = mouse;
        RibbonTask home = new RibbonTask("Task", homeBandArray);
        this.getRibbon().addTask(home);
    }

Regards,
Erling

**Comment by kirill-grouchnikov** [comment]
Ah yes. I see it now.

**Comment by kirill-grouchnikov** [comment]
Also see https://github.com/kirill-grouchnikov/flamingo/issues/2

**Comment by kirill-grouchnikov** [comment]
This particular issue should be addressed in the latest prebuilts of Flamingo and Substance Flamingo plugin (you'll need both). The rest of the work will be done a bit later in February / March as part of the other issue.
