### ISSUE TITLE
The Linux sync thing

### ISSUE THREAD

**Issue by stefan-reich** [kirill-grouchnikov/substance#14]
Hi Kirill :)

There is a known issue for Java on Linux, namely that its video buffers aren't always synced promptly (there is some delay <1 s).

This makes, for example, the smooth scroll bar animations appear choppy sometimes. [[Example]](http://tinybrain.de:8080/tb/show-snippet.php?id=1006964)

Moving the mouse in the window constantly seems to make the animations smooth again.

I have, at times, been calling Toolkit.getDefaultToolkit().sync() explicitly which causes the buffers to be drawn instantly. However, in the case of the scroll bar animation, I wouldn't know how to do that.

Any thoughts on this? It would be nice to see this fixed for sure.

**Comment by kirill-grouchnikov** [comment]
That example is not very useful as it's not a standalone Swing sample.

I'll need a bit more information, and ideally a full sample as well:
* Version of Substance
* Version of OS
* Version of Java
* Specific scenario where scroll bar animations are choppy

Note that scrollbar appearance has been changed quite significantly in the latest 7.0 release

**Comment by stefan-reich** [comment]
Thanks Kirill, nevermind, it's not worth bothering at this point :-)
