### ISSUE TITLE
Substance Repository

### ISSUE THREAD

**Issue by IvanRF** [kirill-grouchnikov/substance#20]
Is your project going to be uploaded to Maven or jcenter? I use Gradle and that would be really helpful.

Current versions:
http://search.maven.org/#search%7Cga%7C1%7Csubstance
https://bintray.com/bintray/jcenter?filterByPkgName=substance

**Comment by IvanRF** [comment]
A related question: is your project going to be uploaded to Maven or jcenter? I use Gradle and that would be really helpful.

Current versions:
http://search.maven.org/#search%7Cga%7C1%7Csubstance
https://bintray.com/bintray/jcenter?filterByPkgName=substance

**Comment by kirill-grouchnikov** [comment]
These things come and go, and I have zero interest in chasing those.

I've been through CVS, SVN and now Git.
I've been on java.net, kenai.com and now github.com.
I've been on Ant through Maven and now Gradle.

I'm not going to chase the latest chic in whatever surrounds the code. And contributors tends to come and go as well. I have zero interest in taking code / scaffolding that I'll have to maintain from that point forward if I have something that already works for me.

**Comment by IvanRF** [comment]
No problem (Maven still works with Gradle). Then, who uploaded your library in the group "org.java.net.substance"? was java.net?

**Comment by kirill-grouchnikov** [comment]
The only thing I know for certain is that it wasn't me.

I do remember that there were similar requests back in the original run of those projects, and as long as I didn't need to do anything, I was fine with people uploading artifacts to wherever they wanted. I can't police those :)

**Comment by IvanRF** [comment]
> as long as I didn't need to do anything, I was fine with people uploading artifacts to wherever they wanted

That's good to know, if it is not me I guess that there will be other users willing to upload Substance updates 😃

**Comment by mtbadi39** [comment]
Hi there
I just created a project to **mavenize** these libraries : i called it [swing-effects](https://github.com/mtbadi39/swing-effects)

**Comment by hmdebenque** [comment]
For all of us maven dependency systems lovers, I used a simple bash script to download and install locally substance and trident:
```
#!/usr/bin/env bash

TRIDENT_VERSION=1.5.00-rc
TRIDENT_LIB_NAME=trident-${TRIDENT_VERSION}.jar

SUBSTANCE_VERSION=8.0.00-rc
SUBSTANCE_LIB_NAME=substance-${SUBSTANCE_VERSION}.jar

curl -O https://raw.githubusercontent.com/kirill-grouchnikov/substance/master/drop/${SUBSTANCE_VERSION}/${TRIDENT_LIB_NAME}
mvn install:install-file -Dfile=${TRIDENT_LIB_NAME} -DgroupId=org.pushingpixels \
        -DartifactId=trident -Dversion=${TRIDENT_VERSION} -Dpackaging=jar

curl -O https://raw.githubusercontent.com/kirill-grouchnikov/substance/master/drop/${SUBSTANCE_VERSION}/${SUBSTANCE_LIB_NAME}
mvn install:install-file -Dfile=${SUBSTANCE_LIB_NAME} -DgroupId=org.pushingpixels \
        -DartifactId=substance -Dversion=${SUBSTANCE_VERSION} -Dpackaging=jar

```

**Comment by kirill-grouchnikov** [comment]
This will be addressed in H1 2019.

**Comment by kirill-grouchnikov** [comment]
Will be tracked in kirill-grouchnikov/radiance#6

See http://www.pushing-pixels.org/2018/05/23/hello-radiance.html for context.
