### ISSUE TITLE
Deployment to Maven Central

### ISSUE THREAD

**Issue by huxi** [kirill-grouchnikov/substance#22]
I'm currently using the [com.github.insubstantial artifacts](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.insubstantial%22) from the [Insubstantial fork](https://github.com/Insubstantial/insubstantial/) via Maven Central.

It would be really helpful if you would deploy your artifacts, too.

Thanks for working on this project again!

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/substance/issues/20

**Comment by huxi** [comment]
Sorry, I overlooked that issue because it was closed.
