### ISSUE TITLE
EmeraldDusk theme disappeared?

### ISSUE THREAD

**Issue by stefan-reich** [kirill-grouchnikov/substance#24]
Hi Kirill, has EmeraldDusk disappeared in latest builds or did I do something wrong? It's the theme for my program starter...

All the best,
Stefan

**Comment by kirill-grouchnikov** [comment]
I've removed Emerald Dusk and Challenger Deep in https://github.com/kirill-grouchnikov/substance/commit/50619d40dd8c9b6232ca82cd652209d5bc12cc9d

They were not up to my standards as far as consistent visuals across all the components. The code in https://github.com/kirill-grouchnikov/substance/commit/50619d40dd8c9b6232ca82cd652209d5bc12cc9d#diff-9b7117ec390767704a969719940baebb should still work as an app-provided skin.

**Comment by stefan-reich** [comment]
Cool. Yeah, the green
