### ISSUE TITLE
JLabel.setForeground

### ISSUE THREAD

**Issue by stefan-reich** [kirill-grouchnikov/substance#25]
Can I still do that? It seems I'm gretting gray labels when Substance is enabled even if I say setForeground(Color.WHITE). Not sure if I'm doing anything wrong.

http://tinybrain.de/1007194
http://tinybrain.de/1007200

With Substance:
![Screenshot](http://eyeocr.sourceforge.net/filestore/filestore.php?cmd=serve&file=blob_1007201&contentType=image/png)

Without Substance:
![Screenshot](http://eyeocr.sourceforge.net/filestore/filestore.php?cmd=serve&file=blob_1007202&contentType=image/png)

BTW, with some twists (and apart of this bug), I got full-screen finally working well with Substance on Linux and Windows now. If anyone is interested: The magic for that is [here](http://tinybrain.de/1004498).

**Comment by kirill-grouchnikov** [comment]
See SubstanceLookAndFeel.COLORIZATION_FACTOR

**Comment by stefan-reich** [comment]
How would I use it? Does it break anything else?

**Comment by IvanRF** [comment]
> How would I use it?

`component.putClientProperty(SubstanceLookAndFeel.COLORIZATION_FACTOR, new Double(factor));`

**Comment by kirill-grouchnikov** [comment]
I don't quite understand the question of "break anything else".

By choosing to use a look-and-feel you choose to have your entire UI rendered by that look-and-feel. If you want to have some parts of your UI use colors that are different from that look, you're already breaking some visual continuity and consistency. 

Substance decoration areas and decoration painters allow to maintain such consistency while also delineating and designating certain areas of your app as "special" ones - such as toolbar or footers for example. If you go lower than that and start setting custom foreground / background colors on specific controls, that might indeed create visual disparities. 

Up to you how far you want to deviate from a Substance skin.

**Comment by stefan-reich** [comment]
I thought it was a global option

**Comment by kirill-grouchnikov** [comment]
As I said, see the COLORIZATION_FACTOR and its Javadocs
