### ISSUE TITLE
Disabling ProgressBar (and other) Animations

### ISSUE THREAD

**Issue by EGjoni** [kirill-grouchnikov/substance#28]
Can't find anything in the docs about how to disable progress bar animations (specifically, how to prevent the progress bar from animating an interpolation between the old value and the new value after setValue() is called).  

Docs state that 

`AnimationConfigurationManager.getInstance().disallowAnimations(.., ..) `

can be used to disable animations on components. But animations persist when doing something like the following: 

```
JButton btnEditColor = new JButton("Color");

AnimationConfigurationManager.getInstance().disallowAnimations(AnimationFacet.ROLLOVER, btnEditColor);
AnimationConfigurationManager.getInstance().disallowAnimations(AnimationFacet.FOCUS, btnEditColor);
AnimationConfigurationManager.getInstance().disallowAnimations(AnimationFacet.FOCUS_LOOP_ANIMATION, btnEditColor);
AnimationConfigurationManager.getInstance().disallowAnimations(AnimationFacet.GHOSTING_BUTTON_PRESS, btnEditColor);
AnimationConfigurationManager.getInstance().disallowAnimations(AnimationFacet.GHOSTING_ICON_ROLLOVER, btnEditColor);
AnimationConfigurationManager.getInstance().disallowAnimations(AnimationFacet.SELECTION, btnEditColor);
AnimationConfigurationManager.getInstance().disallowAnimations(AnimationFacet.PRESS, btnEditColor);
```

I'm not sure if AnimationConfigurationManager is broken or if I'm just misunderstanding how to use it properly

**Comment by kirill-grouchnikov** [comment]
I'm going to add a bit of class-level comments in AnimationConfigurationManager about what can be controlled by its APIs.

Specifically, you have fine-grained controls over two classes of animations:
1. Renderer-based controls such as tables, trees and lists
2. Custom animations that Substance adds such as focus loop, icon glow etc

It would add too much runtime overhead to support such fine-grained control to every base facet (rollover, selection, press) of every single view. That is why you cannot turn off rollover animation, for instance, for a specific button.

**Comment by EGjoni** [comment]
I'm a bit unclear. Does this mean that progressbar interpolation animations
cannot be disabled?

**Comment by kirill-grouchnikov** [comment]
Correct. You can call AnimationConfigurationManager.setTimelineDuration and pass 0, but that would effectively disable all Substance animations.
