### ISSUE TITLE
3rd party library

### ISSUE THREAD

**Issue by plingsi** [kirill-grouchnikov/substance#39]
Hi,
We use a 3rd party library for viewing maps. This library does not support scaling. It works fine in Windows, but in OSX the maps are blurry. Do you have any ideas how this can be solved? Where to start?

Regards,
Erling Fagerlie

**Comment by kirill-grouchnikov** [comment]
I wouldn't really know. Contact the developers of that library?

**Comment by plingsi** [comment]
Done that, but with no luck.

**Comment by kirill-grouchnikov** [comment]
The underlying implementation in Substance was taken from how IntelliJ IDEA is doing it, and I need to revisit that for Java 9, since it has an official API to query the scaling factor.

Otherwise this is something that needs to be done explicitly in each library / app.
