### ISSUE TITLE
JOptionPane Memory Leak

### ISSUE THREAD

**Issue by PirolA** [kirill-grouchnikov/substance#4]
Hi Kirill,

I reported the problem before. However, it was here a memory problem with JDialog. It seems the OptionPane also remains in memory.
You gave me the classes

> Kirill
> 
> Two immediate places that come to mind:
> - SubstanceRootPaneUI
> - RootPaneDefaultButtonTracker

I have inserted the code attached in the SubstanceRootPaneUI#uninstallListener() method.
Do JOptionPane and JDialog behave differently based on the default button?
I need a tip, so that JOptionPane does not remain in memory!

Attached Code:
<code>
RootPaneDefaultButtonTracker tracker = RootPaneDefaultButtonTracker.trackers.get(jButton);
if (tracker != null) {
    tracker.stopTimer();
    tracker.buttonRef.clear();
}
RootPaneDefaultButtonTracker.trackers.remove(jButton);
</code>

Best regards,
Pirol Aydin

**Comment by kirill-grouchnikov** [comment]
Please reopen if this is still happening under the latest dev builds with complete, small and standalone sample that reproduces this issue.
