### ISSUE TITLE
Bug Graphite Chalk border?

### ISSUE THREAD

**Issue by RealAquilus** [kirill-grouchnikov/substance#40]
Hi, i have noticed that only Graphite Chalk as this colored border. is this a bug or is it intentional?
![immagine](https://user-images.githubusercontent.com/20306523/30445996-2689f34c-9988-11e7-8ef5-ebdbc0c59d49.png)
I guess is not intentional it seems pretty "strange".
If need i can post the code but i guess is not necessary it is just a blank form with just the LaF.

**Comment by kirill-grouchnikov** [comment]
That skin does use light-colored borders, so that's intended. But it should be on all four sides. 

I'll need to check how this looks like on non-Retina / non hi-dpi screens. Maybe I'm missing the lines there under that mode.

**Comment by kirill-grouchnikov** [comment]
Please attach a small standalone sample that shows this issue under the latest 7.1 dev build.

**Comment by RealAquilus** [comment]
I forgot to write it, this in in the stable 7.0.01 build, i haven't tested the 7.1, i will check this evening with it an will post the code here.

**Comment by RealAquilus** [comment]
Tested right now the bug still exist in the 7.1 dev. The code is:
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testsubstance;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Andrea_F
 */
public class TestSubstance extends javax.swing.JFrame
{

    /**
     * Creates new form TestSynthetica
     */
    public TestSubstance()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try
                {
                    UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceGraphiteChalkLookAndFeel");
                } catch (ClassNotFoundException ex)
                {
                    Logger.getLogger(TestSubstance.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex)
                {
                    Logger.getLogger(TestSubstance.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex)
                {
                    Logger.getLogger(TestSubstance.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex)
                {
                    Logger.getLogger(TestSubstance.class.getName()).log(Level.SEVERE, null, ex);
                }
                new TestSubstance().setVisible(true);
            }
        });
    }
}
Created using the NetBeans Form designer (version 8.2) but tested in eclipse without designer too, nothing changed.
Hope this help. If you need some other test i will do as fast as i can.

**Comment by RealAquilus** [comment]
A little update: if i resize the form to a lower res the full border appear.
![as](https://user-images.githubusercontent.com/20306523/30478706-6290eee2-9a12-11e7-90e4-a91becdd5f4f.JPG)

**Comment by kirill-grouchnikov** [comment]
I'm not seeing this behavior. What is the version of OS and Java runtime that you're running?

**Comment by RealAquilus** [comment]
Sorry for the delay i was unable to get to the pc these days.
Anyway:
Windows 7 Ultimate (Build 76001, service pack 1)
Java 8 Update 141.

**Comment by kirill-grouchnikov** [comment]
Should be fixed in 7.1.00 release
