### ISSUE TITLE
Cannot easily change icons in JOptionPane

### ISSUE THREAD

**Issue by enwired** [kirill-grouchnikov/substance#41]
In most Swing LAFs, it is possible to change the icons in `JOptionPane` by code such as this:

  `UIManager.getDefaults().put("OptionPane.questionIcon", new MyFancyIcon());`

This does not work in Substance 7.1.

One workaround is to override the `SubstanceOptionPaneUI` class and use

    `UIManager.getDefaults().put("OptionPaneUI", MyOptionPaneUI.class.getCanonicalName());`

and in `MyOptionPaneUI`, override `"getIconForType()"`.

**Comment by enwired** [comment]
Of course, the JOptionPane class always allows users to explicitly specify an icon.  So this "issue" only exists for cases where the programmer does not explicitly specify an icon.

I don't consider this a "bug".  I only reported it as something that has different behavior between this version of Substance and previous versions.

**Comment by kirill-grouchnikov** [comment]
I've added an entry in https://github.com/kirill-grouchnikov/substance/blob/master/www/docs/faq.md that talks about UIManager / UIDefaults and how none of that is considered part of official API for Substance or any other look-and-feel.

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/substance/issues/53

**Comment by kirill-grouchnikov** [comment]
All icons that Substance is using on color choosers, file choosers and its widgets (contextual edit actions, menu search etc) will be customizable with icon packs. SubstanceLookAndFeel.setIconPack is the current point of entry. The API itself is subject to change in the next few weeks in the 8.0dev branch.
