### ISSUE TITLE
Layout issues in ColorPicker UI

### ISSUE THREAD

**Issue by enwired** [kirill-grouchnikov/substance#47]
In the UI for the ColorPicker, in the panel with the Xoetrope color wheel, one of the text boxes does not have enough height to display the text.  (It is the textbox with the hexadecimal color value.  May depend on font and Windows display settings.  I use the Display setting "Medium 125%".)

There is also a tiny button "reset the color wheel saturation and brightness" that doesn't seem to do anything.

In the panel with RGB sliders, there should probably be a small gap added between the sliders and the text boxes.

**Comment by kirill-grouchnikov** [comment]
Do you mind attaching a screenshot of how it looks like under that display setting?

**Comment by enwired** [comment]
![colorpicker](https://user-images.githubusercontent.com/2030338/31745959-d16c2c0c-b419-11e7-8d84-7c2538abebb2.PNG)

**Comment by kirill-grouchnikov** [comment]
I'll replace the reset button (that looks like a checkbox) with a circular arrow icon. The purpose of this control is to reset the color wheel state after using CTRL+drag on one or both of the sliders. Ctrl-dragging changes the saturation and / or brightness of the entire wheel, and that reset brings it back to full values.

**Comment by enwired** [comment]
Ok, thanks.  I didn't know about the Ctrl-dragging so it looked like that button had no effect.

I've also noticed that if you right-click in the colored field just below "Use web safe ..." a pop-up will list colors related to the current Substance skin.  While that is useful for programmers, it probably isn't useful for end users of programs created with Substance.  Whether you want to remove that or not is totally up to you.

**Comment by kirill-grouchnikov** [comment]
The list of "control" colors shown when you click on that colored label is intentional by the original author of the code. Other issues should be addressed with the latest drop of 8.0.0-dev.
