### ISSUE TITLE
Java 9 Issue?

### ISSUE THREAD

**Issue by Flinner** [kirill-grouchnikov/substance#57]
### Version of Substance
7.3
### Version of Java
9.0.1
### Version of OS
macOS 10.13.1
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Hi, I was trying to compile a Minecraft custom launcher by https://github.com/SKCraft/Launcher. I successfully compiled the launcher, but upon running it I get these errors:

https://pastebin.com/TUJTJft5

I asked the developer who created the launcher, and he replied that it's an issue with substance and java 9.  I'm quite inexperienced to programming. But I do want to get it work. Please let me know anything could possibly resolve this issue thanks!!!

**Comment by Flinner** [comment]
In the build script, I did include the latest substance version

apply plugin: 'com.github.johnrengelman.shadow'

jar {
    manifest {
        attributes("Main-Class": "com.skcraft.launcher.FancyLauncher")
    }
}

dependencies {
    compile project(':launcher')
    compile 'com.github.insubstantial:substance:7.3'
}

shadowJar {
    dependencies {
        exclude(dependency('org.projectlombok:lombok'))
    }
}

build.dependsOn(shadowJar)

**Comment by kirill-grouchnikov** [comment]
This is using Insubstantial, and old an no longer maintained fork of Substance.

I will comment on the original issue you opened on that launcher to ask them if they'd be interested in tracking the latest stable release of Substance.
