### ISSUE TITLE
Make available in maven 

### ISSUE THREAD

**Issue by johann-petrak** [kirill-grouchnikov/substance#58]
In order to use the library from a Maven-managed project the jars and all dependencies should 
be available in Maven. Are there plans to make substance available on Maven central?

**Comment by IvanRF** [comment]
See #20

**Comment by johann-petrak** [comment]
Well Maven is not really a "latest chic", it is the infrastructure for managing dependencies which is is used by practically everyone by now and is the foundation of not just the Maven build tool itself but ivy, sbt, gradle and a couple more. 
I think it would be a pity to limit the acceptance and popularity of this project by making it hard for those many who rely on the Maven infrastructure to include the software into their projects.

**Comment by kirill-grouchnikov** [comment]
There's the thing, and then there's the things around the thing.

I'm only interested in doing the thing itself. I don't have any plans to spend any time on the things around it.

**Comment by johann-petrak** [comment]
Would you also be opposed to accepting a pull request for mavenizing the build and subsequently somebody else taking care of pushing to Maven central? This may involve mavenizing the Trident build as well as this project depends on it.

**Comment by kirill-grouchnikov** [comment]
Yes
