### ISSUE TITLE
Window can't be moved between displays

### ISSUE THREAD

**Issue by mguillem** [kirill-grouchnikov/substance#6]
Running an application with Substance 6.1 LAF, I can't move the windows from one display to an other (I'm using 2 monitors): it happens as would the application only consider the screen where it is displayed. If I remove Substance LAF everything works fine.

I'm using Java 1.6.0_22 on Ubuntu 10.10 64bits.

**Comment by kirill-grouchnikov** [comment]
No access to Ubuntu for developing. If this is still happening under the latest dev builds, patches welcome.
