### ISSUE TITLE
Writing Japanese text fails when using Substance

### ISSUE THREAD

**Issue by brad-eric** [kirill-grouchnikov/substance#68]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc):
When i use the default system look & feel, and click Browse to select a file i select a file with a Japanese name and its Japanese name appears fine in the JTextField. If i use a Substance look and feel, select the same file, its name appears as blocks in the JTextField.

Screenshots attached.

Is there a way to fix this in Substance? And can substance controls show text of any language?

Cheers,
Brad
![substance l f](https://user-images.githubusercontent.com/1052828/35055523-11017580-fbb8-11e7-9ebd-1b31e72486d2.jpg)
![system l f](https://user-images.githubusercontent.com/1052828/35055524-112a83ee-fbb8-11e7-8bdf-3357b036e6c5.jpg)

**Comment by nroduit** [comment]
I guess it because of the specific font associated with the L&F. After the L&F has been applied, try to set the default font which contains asiatic characters:
`LookAndFeels.setUIFont(new javax.swing.plaf.FontUIResource(Font.SANS_SERIF, Font.PLAIN, 12));`

**Comment by kirill-grouchnikov** [comment]
Will be tracked in kirill-grouchnikov/radiance#4

See http://www.pushing-pixels.org/2018/05/23/hello-radiance.html for context.
