### ISSUE TITLE
NPE in SubstanceTreeUI

### ISSUE THREAD

**Issue by ghost** [kirill-grouchnikov/substance#7]
I recently set up a JTree with drag and drop support and found that in Substance 6.1 SubstanceTreeUI throws an exception when either there is only one node in the tree and you drag it, or when you try to drag a node onto an empty tree.  This is happening at line 524, as the code is not taking into account the possibility that the oldBounds returned by getPathBounds(tree, oldDrop) can return null.

**Comment by kirill-grouchnikov** [comment]
Please reopen if this is still happening under the latest dev builds with complete, small and standalone sample that reproduces this issue.
