### ISSUE TITLE
Possible to change scroll bar style?

### ISSUE THREAD

**Issue by ajaymills** [kirill-grouchnikov/substance#76]
### Version of Substance

7.1.01

### Version of Java

9.04

### Version of OS

Windows 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Sorry for what's probably a stupid question.

It looks like in this release of Substance all the scroll bars have by default a rounded, thin look and lacking the button arrows. Is it possible to switch to the thick, boxy style of insubstantial? Example: 

https://insubstantial.github.io/insubstantial/substance/docs/skins/toneddown.html

**Comment by kirill-grouchnikov** [comment]
That look is no longer supported. http://www.pushing-pixels.org/2016/12/22/hello-substance-my-old-friend.html has more details on the reasons behind removing the visual noise in Substance starting with version 7.0.
