### ISSUE TITLE
How to apply custom FontSets?

### ISSUE THREAD

**Issue by utybo** [kirill-grouchnikov/substance#81]
Is there a way to apply a custom font set to a theme? I wish to force a specific font in my app to have consistancy across all OSes. Is this currently possible? I have searched but I'm a little confused...

**Comment by kirill-grouchnikov** [comment]
Font sets are orthogonal to themes. The font policy passed to SubstanceCortex.GlobalScope.setFontPolicy will apply to all the UI elements in all the windows. You should call that method before creating your first window.

**Comment by kirill-grouchnikov** [comment]
Font sets are orthogonal to themes. The font policy passed to SubstanceCortex.GlobalScope.setFontPolicy will apply to all the UI elements in all the windows. You should call that method before creating your first window.

**Comment by utybo** [comment]
OK, thank you!
