### ISSUE TITLE
Not possible to change alpha value for color with color picker

### ISSUE THREAD

**Issue by deathbeam** [kirill-grouchnikov/substance#84]
### Version of Substance
```
8.0.00-dev
```

### Version of Java
```
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

### Version of OS
```
Darwin i386
```

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
When using Substance Twillight theme (with colorscheme slightly modified, but the issue happens also with Graphite theme) the slider for alpha value of the color is missing from the color picker, even though when using the default Swing theme, the color picker contains slider for alpha value of the color.

Screenshots:
![screenshot 2018-04-09 18 42 57](https://user-images.githubusercontent.com/5115805/38510886-a49e21ae-3c26-11e8-9ae2-b526bd62493d.png)

![screenshot 2018-04-09 18 43 18](https://user-images.githubusercontent.com/5115805/38510837-8723f892-3c26-11e8-83d4-b80521534624.png)

![screenshot 2018-04-09 18 43 14](https://user-images.githubusercontent.com/5115805/38510838-876647ec-3c26-11e8-844c-6213db0b1aff.png)

**Comment by utybo** [comment]
You should probably try to update Substance to the latest versions

**Comment by kirill-grouchnikov** [comment]
Most of the color selector panels do not lend themselves well to displaying an additional slider. Having it in a few, but not in the majority is not a good UX.

**Comment by deathbeam** [comment]
Is there any alternative to color picker in substance what has the alpha slider? Or any way to use the default one instead? Having slider for alpha is very important for me in this case. Also, I don't think closing this issue is good idea, it could've also server as reference for other people with similar question.

**Comment by kirill-grouchnikov** [comment]
I don't leave issues open if they have a resolution on my side. Otherwise the issue tracker becomes quite unmanageable. 

For now the rather awkward workaround would be to use substance-lite.jar binary instead of the full one. I will consider adding a SubstanceCortex.GlobalScope API to have the app decide whether to use the default Swing color chooser or Substance-specific one.
